### ISSUE TITLE
Code highlighting and similarities for small code

### ISSUE THREAD

**Issue by DomrinaV** [blingenf/copydetect#26]
Hello! While using copydetect on small solutions, I have found some cases with highlighting which seemed to miss some matching parts and similarities less than 70% (and 50% if more constructions are changed), changing thresholds didn't help. At first, I thought that this was the fault of {} brackets and changing ++ to +=1, but that is not the case for highlighting. I would like to know whether that is a limitation of the winnowing algorithm or something that can be fixed.

With sol and sol2, I renamed the variables, added an unused one and changed n++ to n+= 1. This let to the following results:
```
>>> fp1 = copydetect.CodeFingerprint("sol.c", 15, 1)
>>> fp2 = copydetect.CodeFingerprint("sol2.c", 15, 1)
>>> token_overlap, similarities, slices = copydetect.compare_files(fp1, fp2)
>>> print(similarities)
(0.47058823529411764, 0.4444444444444444)
>>> code1, _ = copydetect.utils.highlight_overlap(fp1.raw_code, slices[0], ">>", "<<")
>>> code2, _ = copydetect.utils.highlight_overlap(fp2.raw_code, slices[1], ">>", "<<")
>>> print(code1)
int num = 0;

if (a0<0)
    num++;

double a>>;

while (fscanf(fin, "%lf", &a) != EOF)
{
    if (a<0)
        num+<<+;
}

return num;

>>> print(code2)
int n = 0;
    double b, c;
    if (a0 < 0)
        n += 1>>;
    while (fscanf(fin, "%lf", &b) != EOF)
    {
        if (b < 0)
            n +<<= 1;
    }
    return n;
```

when i changed n+=1 to n++ in sol3, similarities got higher, but the highlighting seemed to miss some important parts:
```
>>> fp1 = copydetect.CodeFingerprint("sol.c", 15, 1)
>>> fp2 = copydetect.CodeFingerprint("sol3.c", 15, 1)
>>> token_overlap, similarities, slices = copydetect.compare_files(fp1, fp2)
>>> print(similarities)
(0.6323529411764706, 0.6142857142857143)
>>> code1, _ = copydetect.utils.highlight_overlap(fp1.raw_code, slices[0], ">>", "<<")
>>> code2, _ = copydetect.utils.highlight_overlap(fp2.raw_code, slices[1], ">>", "<<")
>>> print(code1)
int num = 0;

if (a0<0)
    num++;

double a>>;

while (fscanf(fin, "%lf", &a) != EOF)
{
    if (a<0)
        num++;
}

return num;<<

>>> print(code2)
int n = 0;
    double b, c;
    if (a0 < 0)
        n ++>>;
    while (fscanf(fin, "%lf", &b) != EOF)
    {
        if (b < 0)
            n ++;
    }
    return n;<<

```
When I added { and } to if constructions in sol4, the result became this:
```
>>> fp1 = copydetect.CodeFingerprint("sol.c", 15, 1)
>>> fp2 = copydetect.CodeFingerprint("sol4.c", 15, 1)
>>> token_overlap, similarities, slices = copydetect.compare_files(fp1, fp2)
>>> print(similarities)
(0.4264705882352941, 0.3918918918918919)
>>> code1, _ = copydetect.utils.highlight_overlap(fp1.raw_code, slices[0], ">>", "<<")
>>> code2, _ = copydetect.utils.highlight_overlap(fp2.raw_code, slices[1], ">>", "<<")
>>> print(code1)
int num = 0;

if (a0<0)
    num++;

double a;

>>while (fscanf(fin, "%lf", &a) != EOF)
{
    if (a<0)
        <<num++;
}

return num;

>>> print(code2)
int n = 0;
    double b, c;
    if (a0 < 0)
    {
        n ++;
    }
    >>while (fscanf(fin, "%lf", &b) != EOF)
    {
        if (b < 0)
        <<{
            n ++;
        }
    }
    return n;

```
Raw code used here:
sol.c:
```
int num = 0;

if (a0<0)
    num++;

double a;

while (fscanf(fin, "%lf", &a) != EOF)
{
    if (a<0)
        num++;
}

return num;
```
sol2.c:
```
int n = 0;
    double b, c;
    if (a0 < 0)
        n += 1;
    while (fscanf(fin, "%lf", &b) != EOF)
    {
        if (b < 0)
            n += 1;
    }
    return n;
```
sol3.c:
```
int n = 0;
    double b, c;
    if (a0 < 0)
        n ++;
    while (fscanf(fin, "%lf", &b) != EOF)
    {
        if (b < 0)
            n ++;
    }
    return n;
```
sol4.c:
```
int n = 0;
    double b, c;
    if (a0 < 0)
    {
        n ++;
    }
    while (fscanf(fin, "%lf", &b) != EOF)
    {
        if (b < 0)
        {
            n ++;
        }
    }
    return n;
```

**Comment by blingenf** [comment]
Unfortunately, this is definitely more of a limitation than an immediately fixable issue. Here are the tokenized versions of those files:

` sol.c: intV=0;if(V<0)V++;doubleV;while(V(V,"S",&V)!=V){if(V<0)V++;}returnV;`
`sol2.c: intV=0;doubleV,V;if(V<0)V+=1;while(V(V,"S",&V)!=V){if(V<0)V+=1;}returnV;`
`sol3.c: intV=0;doubleV,V;if(V<0)V++;while(V(V,"S",&V)!=V){if(V<0)V++;}returnV;`
`sol4.c: intV=0;doubleV,V;if(V<0){V++;}while(V(V,"S",&V)!=V){if(V<0){V++;}}returnV;`

The detection algorithm is pretty simple -- with a threshold of 15, it is looking for matching sequences of 15 characters between two of these strings. Even minor changes such as the `+=` change or adding brackets around an if will disrupt that.

The core limitation here is that the tokenizer considers only syntax. Comments and whitespace are easy to get rid of because they are syntactically distinct, renamed variables and methods are easy to deal by replacing each with a generic token (`V`), and large sections of code which have been moved around are easy to detect because the algorithm doesn't consider where in the code the sequences of 15 are. But recognizing unused variables and unnecessary brackets would require looking at the code at a far more advanced level than copydetect is able to do.

**Comment by DomrinaV** [comment]
Thank you for the answer!
