### ISSUE TITLE
Code comparison for files not being done correctly for xml files.

### ISSUE THREAD

**Issue by anushadeloitte** [blingenf/copydetect#9]
Hi,
I have used the above library to compare my files for xml files. even though 2 files have the same code, the library does not show it as copied. I have used the default configuration for the same.
![image](https://user-images.githubusercontent.com/92379953/161525646-a9d3c496-dbdd-4135-a24e-bd56c234b328.png)

Please let me know if there are some changes to be done.

Note: the same issue is persisted in a few .properties and java files as well

Thank you in advance

**Comment by blingenf** [comment]
Thank you for the report. There seems to be two things happening here:

- pygments tokenizes text between XML tags as `token.Text`, which is ignored for code comparison. The package explicitly filters these for a reason -- for most languages they're just whitespace, which pygments does have a specific token for but if I recall correctly this misses a few things that shouldn't be considered for code comparison. I'll double check this and see if there's a better way of handling text tokens.
- Comparison is computed using the number of overlapping 25-token (or whatever other size your noise threshold is) fingerprints. Because the above issue removes all text between the tags, all copydetect sees is the same tags over and over. Copydetect only considers the _unique_ fingerprints in a file, so it finds the first of these duplications and ignores the rest. Duplicate fingerprints are rare in normal code so in general this shouldn't be an issue, but I think there's a better way or handling this so I'll look into that as well.

**Comment by blingenf** [comment]
It looks like there isn't a good way to improve how XML files are tokenized -- any change to how text tokens are handled causes issues for most other languages. If you're only comparing XML I'd recommend using the `-f` flag, which will disable tokenization (i.e., files will be treated as plain text).

That said, it looks like after updating the similarity score to better handle duplicate fingerprints (#10) duplicate XMLs are correctly detected with our without filtering. @anushadeloitte if you install copydetect from the `fix/similarity_score` branch does that fix your issue?
